version: "3.8"
services:
  nextjs-app:
    build: .
    container_name: bangundatar-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./edu.db
    volumes:
      - ./edu.db:/app/edu.db
