services:
  nextjs-app:
    build: .
    container_name: bangundatar-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Gunakan path absolut di dalam container
      - DATABASE_URL=file:/app/data/edu.db
    volumes:
      # Arahkan ke folder, bukan langsung ke file agar lebih stabil
      - nextjs_db_data:/app/data

volumes:
  nextjs_db_data:
