import {
  Sun,
  Cloud,
  Star,
  BookOpen,
  Target,
  Zap,
  Hexagon,
  Rocket,
  Diamond,
  Sparkles,
  Circle,
  Square,
  Triangle,
  MousePointer2,
  Lightbulb,
  Trophy,
  Puzzle,
  Microscope,
  Pencil,
  Palette,
  Globe,
  Heart,
  Ghost,
  Crown,
  Coffee,
  Gift,
  Music,
  Camera,
  CloudLightning,
  Bell,
  Anchor,
  Bike,
  Binoculars,
  Bomb,
  Briefcase,
  Bug,
  Bus,
  Car,
  Compass,
  Cpu,
  Database,
  Eye,
  Feather,
  Flag,
  FlaskConical,
  Flower2,
  Gamepad2,
  Gauge,
  Hammer,
  Moon,
  Bird,
  Wind,
  ChartNoAxesCombined,
} from "lucide-react";

export const decorations = [
  // --- GRUP 1: LANGIT & ATMOSFER (1-10) ---
  {
    icon: <Sun size={100} />,
    className: "top-[2%] left-[2%] text-yellow-400 opacity-20",
    animate: { rotate: 360 },
    transition: { duration: 25, repeat: Infinity, ease: "linear" },
  },
  {
    icon: <Cloud size={120} />,
    className: "top-[10%] right-[5%] text-blue-100 opacity-30",
    animate: { x: [-40, 40] },
    transition: { duration: 10, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <CloudLightning size={80} />,
    className: "top-[15%] left-[15%] text-blue-200 opacity-20",
    animate: { opacity: [0.1, 0.4, 0.1] },
    transition: { duration: 2, repeat: Infinity },
  },
  {
    icon: <Star size={20} fill="currentColor" />,
    className: "top-[5%] left-[30%] text-yellow-200 opacity-40",
    animate: { scale: [0.5, 1.2, 0.5] },
    transition: { duration: 3, repeat: Infinity },
  },
  {
    icon: <Star size={25} fill="currentColor" />,
    className: "top-[20%] right-[35%] text-yellow-100 opacity-30",
    animate: { opacity: [0.2, 0.8, 0.2] },
    transition: { duration: 4, repeat: Infinity, delay: 1 },
  },
  {
    icon: <Rocket size={50} />,
    className: "top-[25%] left-[5%] text-brand-primary opacity-15",
    animate: { y: [0, -100], x: [0, 50], opacity: [0, 0.2, 0] },
    transition: { duration: 8, repeat: Infinity },
  },
  {
    icon: <Sparkles size={30} />,
    className: "top-[8%] right-[20%] text-yellow-300 opacity-40",
    animate: { rotate: 180 },
    transition: { duration: 5, repeat: Infinity },
  },
  {
    icon: <Moon size={40} />,
    className: "top-[2%] right-[15%] text-indigo-100 opacity-10",
    animate: { scale: [1, 1.1, 1] },
    transition: { duration: 6, repeat: Infinity },
  },
  {
    icon: <Bird size={35} />,
    className: "top-[12%] left-[45%] text-sky-300 opacity-20",
    animate: { x: [0, 100], y: [0, -20, 0] },
    transition: { duration: 12, repeat: Infinity },
  },
  {
    icon: <Wind size={50} />,
    className: "top-[18%] right-[45%] text-gray-100 opacity-10",
    animate: { x: [-100, 100] },
    transition: { duration: 15, repeat: Infinity },
  },

  // --- GRUP 2: PERALATAN BELAJAR & IDE (11-20) ---
  {
    icon: <Lightbulb size={45} />,
    className: "top-[30%] right-[10%] text-amber-400 opacity-25",
    animate: { scale: [1, 1.2, 1] },
    transition: { duration: 3, repeat: Infinity },
  },
  {
    icon: <BookOpen size={40} />,
    className: "top-[40%] left-[8%] text-emerald-400 opacity-20",
    animate: { y: [0, -15, 0] },
    transition: { duration: 5, repeat: Infinity },
  },
  {
    icon: <Pencil size={30} />,
    className: "top-[35%] left-[25%] text-gray-400 opacity-15",
    animate: { rotate: [0, 15, 0] },
    transition: { duration: 4, repeat: Infinity },
  },
  {
    icon: <FlaskConical size={40} />,
    className: "top-[50%] right-[5%] text-purple-400 opacity-20",
    animate: { rotate: [-10, 10] },
    transition: { duration: 6, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Microscope size={45} />,
    className: "bottom-[40%] left-[3%] text-cyan-500 opacity-15",
    animate: { scale: [0.9, 1.1] },
    transition: { duration: 7, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Palette size={40} />,
    className: "top-[45%] right-[25%] text-pink-400 opacity-20",
    animate: { rotate: 360 },
    transition: { duration: 20, repeat: Infinity, ease: "linear" },
  },
  {
    icon: <Globe size={50} />,
    className: "bottom-[35%] right-[15%] text-blue-400 opacity-15",
    animate: { rotate: -360 },
    transition: { duration: 30, repeat: Infinity, ease: "linear" },
  },
  {
    icon: <Compass size={35} />,
    className: "top-[60%] left-[12%] text-orange-400 opacity-20",
    animate: { rotate: [0, 360] },
    transition: { duration: 10, repeat: Infinity },
  },
  {
    icon: <Briefcase size={30} />,
    className: "top-[70%] right-[10%] text-brown-400 opacity-10",
    animate: { y: [0, 10, 0] },
    transition: { duration: 5, repeat: Infinity },
  },
  {
    icon: <Feather size={35} />,
    className: "top-[55%] left-[30%] text-slate-300 opacity-20",
    animate: { x: [0, 20, 0], y: [0, 20, 0] },
    transition: { duration: 6, repeat: Infinity },
  },

  // --- GRUP 3: GEOMETRI & LOGIKA (21-30) ---
  {
    icon: <Hexagon size={60} />,
    className: "top-[30%] left-[50%] text-emerald-200 opacity-10",
    animate: { rotate: 360 },
    transition: { duration: 15, repeat: Infinity, ease: "linear" },
  },
  {
    icon: <Triangle size={40} />,
    className: "bottom-[45%] left-[20%] text-red-200 opacity-20",
    animate: { rotate: [0, 90, 0] },
    transition: { duration: 8, repeat: Infinity },
  },
  {
    icon: <Square size={40} />,
    className: "bottom-[50%] right-[30%] text-blue-200 opacity-20",
    animate: { scale: [1, 1.3, 1] },
    transition: { duration: 5, repeat: Infinity },
  },
  {
    icon: <Diamond size={50} />,
    className: "bottom-[30%] left-[35%] text-purple-200 opacity-15",
    animate: { y: [-20, 20] },
    transition: { duration: 4, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Puzzle size={40} />,
    className: "bottom-[25%] left-[10%] text-indigo-200 opacity-20",
    animate: { rotate: [-20, 20] },
    transition: { duration: 5, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Target size={55} />,
    className: "top-[10%] left-[60%] text-rose-200 opacity-15",
    animate: { scale: [1, 1.1, 1] },
    transition: { duration: 3, repeat: Infinity },
  },
  {
    icon: <Cpu size={40} />,
    className: "bottom-[40%] right-[40%] text-slate-400 opacity-10",
    animate: { opacity: [0.1, 0.3, 0.1] },
    transition: { duration: 4, repeat: Infinity },
  },
  {
    icon: <Database size={35} />,
    className: "bottom-[15%] right-[45%] text-blue-300 opacity-10",
    animate: { y: [5, -5] },
    transition: { duration: 3, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Hammer size={30} />,
    className: "top-[75%] left-[5%] text-orange-200 opacity-15",
    animate: { rotate: [-30, 0] },
    transition: { duration: 2, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Gauge size={35} />,
    className: "top-[25%] right-[25%] text-emerald-100 opacity-20",
    animate: { rotate: [-90, 90] },
    transition: { duration: 5, repeat: Infinity, repeatType: "mirror" },
  },

  // --- GRUP 4: HOBI & GAME (31-40) ---
  {
    icon: <Gamepad2 size={50} />,
    className: "bottom-[10%] left-[5%] text-brand-primary opacity-10",
    animate: { y: [0, -10, 0] },
    transition: { duration: 4, repeat: Infinity },
  },
  {
    icon: <Trophy size={45} />,
    className: "bottom-[20%] right-[3%] text-yellow-500 opacity-20",
    animate: { scale: [1, 1.2, 1] },
    transition: { duration: 3, repeat: Infinity },
  },
  {
    icon: <Music size={35} />,
    className: "bottom-[5%] left-[20%] text-pink-300 opacity-25",
    animate: { rotate: [0, 20, -20, 0] },
    transition: { duration: 5, repeat: Infinity },
  },
  {
    icon: <Camera size={30} />,
    className: "bottom-[15%] right-[20%] text-gray-300 opacity-15",
    animate: { opacity: [0.2, 0.5, 0.2] },
    transition: { duration: 4, repeat: Infinity },
  },
  {
    icon: <Gift size={40} />,
    className: "bottom-[8%] right-[35%] text-red-400 opacity-15",
    animate: { scale: [0.8, 1], rotate: [-10, 10] },
    transition: { duration: 5, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Bike size={45} />,
    className: "bottom-[2%] left-[40%] text-emerald-300 opacity-10",
    animate: { x: [-50, 50] },
    transition: { duration: 10, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Ghost size={35} />,
    className: "top-[40%] left-[40%] text-purple-100 opacity-10",
    animate: { x: [-20, 20], y: [0, -10, 0] },
    transition: { duration: 4, repeat: Infinity },
  },
  {
    icon: <Bug size={30} />,
    className: "bottom-[30%] right-[25%] text-red-200 opacity-10",
    animate: { rotate: 360 },
    transition: { duration: 12, repeat: Infinity, ease: "linear" },
  },
  {
    icon: <Binoculars size={40} />,
    className: "top-[65%] right-[25%] text-indigo-300 opacity-15",
    animate: { scale: [1, 1.1, 1] },
    transition: { duration: 6, repeat: Infinity },
  },
  {
    icon: <Gamepad2 size={30} />,
    className: "top-[80%] right-[15%] text-brand-secondary opacity-10",
    animate: { rotate: 15 },
    transition: { duration: 2, repeat: Infinity, repeatType: "mirror" },
  },

  // --- GRUP 5: OBJEK UMUM & AKSEN (41-50) ---
  {
    icon: <Heart size={25} fill="currentColor" />,
    className: "bottom-[2%] right-[5%] text-red-300 opacity-20",
    animate: { scale: [1, 1.3, 1] },
    transition: { duration: 2, repeat: Infinity },
  },
  {
    icon: <Coffee size={35} />,
    className: "bottom-[25%] left-[25%] text-brown-200 opacity-10",
    animate: { y: [0, -5, 0] },
    transition: { duration: 3, repeat: Infinity },
  },
  {
    icon: <Bell size={30} />,
    className: "top-[5%] left-[60%] text-yellow-200 opacity-15",
    animate: { rotate: [-15, 15] },
    transition: { duration: 1, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Anchor size={40} />,
    className: "bottom-[40%] left-[45%] text-blue-200 opacity-10",
    animate: { rotate: [-5, 5] },
    transition: { duration: 4, repeat: Infinity, repeatType: "mirror" },
  },
  {
    icon: <Flag size={35} />,
    className: "top-[2%] left-[80%] text-red-200 opacity-15",
    animate: { skewX: [0, 10, 0] },
    transition: { duration: 3, repeat: Infinity },
  },
  {
    icon: <Flower2 size={40} />,
    className: "bottom-[12%] left-[60%] text-pink-200 opacity-15",
    animate: { rotate: 360 },
    transition: { duration: 15, repeat: Infinity, ease: "linear" },
  },
  {
    icon: <Bus size={40} />,
    className: "bottom-[5%] right-[10%] text-orange-200 opacity-10",
    animate: { x: [0, 20, 0] },
    transition: { duration: 5, repeat: Infinity },
  },
  {
    icon: <Eye size={30} />,
    className: "top-[50%] left-[20%] text-gray-200 opacity-10",
    animate: { opacity: [0.1, 0.4, 0.1] },
    transition: { duration: 5, repeat: Infinity },
  },
  {
    icon: <ChartNoAxesCombined size={35} />,
    className: "bottom-[55%] right-[18%] text-brand-primary opacity-10",
    animate: { rotate: 360 },
    transition: { duration: 20, repeat: Infinity, ease: "linear" },
  },
  {
    icon: <MousePointer2 size={25} />,
    className: "top-[70%] left-[40%] text-gray-300 opacity-20",
    animate: { x: [0, 30, 0], y: [0, 30, 0] },
    transition: { duration: 8, repeat: Infinity },
  },
];
